---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "plexor.gename" . }}
  labels:
{{ include "plexor.labels" . | indent 4 }}
spec:
  selector:
{{ include "plexor.selectorLabels" . | indent 6 }}
  ports:
  - protocol: TCP
    port:  {{ .Values.ports.http }}
    targetPort: rtsp
    name: rtsp
  sessionAffinity: ClientIP
